---
title: "Abundance Modelling"
author: "Kwasi Wrensford"
date: "2025-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
library(vroom)
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(forcats)
library(lubridate)
library(MASS)
library(hms)
library(unmarked)
library(camtrapR)
library(overlap)
library(stars)
library(Rcpp)
library(stringr)
library(mgcv)
library(cowplot)
library(gridExtra)
library(ubms)
library(MCMCvis)
library(sjPlot)
library(sjmisc)
library(ggeffects)
library(cmdstanr)
library(ggimage)
library(cowplot)
library(patchwork)
library(grid)
library(magick)
```

#Formatting count data

```{r}

coyotecounts <- as.matrix(read.csv("data/coyotecounts.csv"))
coyotecounts_boreal <- as.matrix(read.csv("data/coyotecounts_boreal.csv"))
coyotecounts_park <- as.matrix(read.csv("data/coyotecounts_park.csv"))


redfoxcounts <- as.matrix(read.csv("data/redfoxcounts.csv"))
redfoxcounts_boreal <- as.matrix(read.csv("data/redfoxcounts_boreal.csv"))
redfoxcounts_park <- as.matrix(read.csv("data/redfoxcounts_park.csv"))

lynxcounts <- as.matrix(read.csv("data/lynxcounts.csv"))
lynxcounts_boreal <- as.matrix(read.csv("data/lynxcounts_boreal.csv"))

martencounts <- as.matrix(read.csv("data/martencounts.csv"))
martencounts_boreal <- as.matrix(read.csv("data/martencounts_boreal.csv"))

fishercounts <- as.matrix(read.csv("data/fishercounts.csv"))
fishercounts_boreal <- as.matrix(read.csv("data/fishercounts_boreal.csv"))



```

#Load in covariate data

```{r}
covars <- read.csv("data/covars.csv")
covars_boreal <- read.csv("data/covars_boreal.csv")
covars_park <- read.csv("data/covars_park.csv")
```

```{r}
covars$PC1<-scale(covars$PC1)
covars$PC2<-scale(covars$PC2)
covars$hf<-scale(covars$hf)
covars$baited <- as.numeric(covars$baited)

covars_boreal$PC1<-scale(covars_boreal$PC1)
covars_boreal$PC2<-scale(covars_boreal$PC2)
covars_boreal$hf<-scale(covars_boreal$hf)
covars_boreal$baited <- as.numeric(covars_boreal$baited)

covars_park$PC1<-scale(covars_park$PC1)
covars_park$PC2<-scale(covars_park$PC2)
covars_park$hf<-scale(covars_park$hf)
covars_park$baited <- as.numeric(covars_park$baited)
```



#Stan N-mixture using ubms
```{r}
##Coyote Boreal
# number of sites and surveys
n_sites <- nrow(coyotecounts_boreal)
n_surveys <- ncol(coyotecounts_boreal)

# convert each site covariate to observation-level
boreal_bait <- matrix(rep(covars_boreal$baited, each = n_surveys), nrow = n_sites)
boreal_cam <- matrix(rep(covars_boreal$location, each = n_surveys), nrow = n_sites)

umf_coyote_boreal <- unmarkedFramePCount(
  y = coyotecounts_boreal,
  siteCovs = covars_boreal,
  obsCovs = list(bait = boreal_bait, camera = boreal_cam)
)

coyote_nmix_ubms_boreal <- stan_pcount(formula =  ~ bait 
                                ~ PC1 * hf + PC2 * hf,
                     data = umf_coyote_boreal,
                     chains = 3,
                     iter = 500,
                     cores = 3)

coyote_nmix_ubms_boreal

saveRDS(coyote_nmix_ubms_boreal, file = "coyote_nmix_ubms_boreal.rds")

plot_effects(coyote_nmix_ubms_boreal, submodel = "state")
plot_effects(coyote_nmix_ubms_boreal, submodel = "det")


traceplot(coyote_nmix_ubms_boreal)

plot_posteriors(coyote_nmix_ubms_boreal)

coyote_gof<-gof(coyote_nmix_ubms_boreal, draws=100)
coyote_gof
```

```{r}
###Predict interaction plot function
plot_interaction_ubms <- function(model,
                                  focal,
                                  moderator,
                                  species = NULL,
                                  submodel = "state",
                                  data,
                                  mod_probs = c(0.25, 0.75),
                                  n = 1000,
                                  ylab = NULL,
                                  xlab = NULL,
                                  title = NULL,
                                  col_low = "darkgreen",
                                  col_high = "darkorange3") {
  
  # 1. Extract moderator quantiles
  mod_vals <- quantile(data[[moderator]], probs = mod_probs, na.rm = TRUE)
  
  # 2. Build prediction grids
  make_grid <- function(mod_value) {
    grid <- data.frame(
      focal = seq(min(data[[focal]], na.rm = TRUE),
                  max(data[[focal]], na.rm = TRUE),
                  length.out = n)
    )
    names(grid)[1] <- focal
    
    # Add moderator
    grid[[moderator]] <- mod_value
    
    # Fix all other covariates at their means
    numeric_covs <- names(data)[sapply(data, is.numeric)]
other_covs <- setdiff(numeric_covs, c(focal, moderator))
    for (v in other_covs) {
      grid[[v]] <- mean(data[[v]], na.rm = TRUE)
    }
    grid
  }
  
  grid_low <- make_grid(mod_vals[1])
  grid_high <- make_grid(mod_vals[2])
  
  # 3. Predict
  pred_low <- ubms::predict(model,
                            submodel = submodel,
                            species = species,
                            newdata = grid_low)
  
  pred_high <- ubms::predict(model,
                             submodel = submodel,
                             species = species,
                             newdata = grid_high)
  
  # 4. Combine into a plotting dataframe
  df <- data.frame(
    cov = grid_low[[focal]],
    pred_lo = pred_low$Predicted,
    lower_lo = pred_low$`2.5%`,
    upper_lo = pred_low$`97.5%`,
    pred_hi = pred_high$Predicted,
    lower_hi = pred_high$`2.5%`,
    upper_hi = pred_high$`97.5%`
  )
  
  # 5. Labels
  if (is.null(ylab)) ylab <- paste("Predicted", species)
  if (is.null(xlab)) xlab <- focal
  #if (is.null(title)) title <- paste("Effect of", focal, "x", moderator)
  
  # 6. Plot
  library(ggplot2)
  ggplot(df, aes(x = cov)) +
    geom_ribbon(aes(ymin = lower_lo, ymax = upper_lo),
                fill = col_low, alpha = 0.2) +
    geom_line(aes(y = pred_lo), color = col_low, linewidth = 1) +
    geom_ribbon(aes(ymin = lower_hi, ymax = upper_hi),
                fill = col_high, alpha = 0.2) +
    geom_line(aes(y = pred_hi), color = col_high, linewidth = 1) +
    labs(y = ylab, x = xlab, title = title) +
    theme_classic() + 
    theme(legend.position = "none")
}
```


```{r}
coyote_boreal__pc1_plot <- plot_interaction_ubms(
  model = coyote_nmix_ubms_boreal,
  focal = "PC1",
  moderator = "hf",
  species = "coyote",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "Coyote abundance vs PC1 at low/high HF"
)

coyote_boreal_pc1_plot
```

```{r}
coyote_boreal_pc2_plot <- plot_interaction_ubms(
  model = coyote_nmix_ubms_boreal,
  focal = "PC2",
  moderator = "hf",
  species = "coyote",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC2",
  title = "Coyote abundance vs PC2 at low/high HF"
)

coyote_boreal_pc2_plot
ggsave(filename = "boreal_coyote_pc1.pdf", coyote_boreal_pc2_plot, device = "pdf")
```

```{r}
##Coyote Park
# number of sites and surveys
n_sites_park <- nrow(coyotecounts_park)
n_surveys_park <- ncol(coyotecounts_park)

# convert each site covariate to observation-level
park_bait <- matrix(rep(covars_park$baited, each = n_surveys_park), nrow = n_sites_park)
park_cam <- matrix(rep(covars_park$location, each = n_surveys_park), nrow = n_sites_park)

umf_coyote_park <- unmarkedFramePCount(
  y = coyotecounts_park,
  siteCovs = covars_park,
  obsCovs = list(bait = park_bait, camera = park_cam)
)

coyote_nmix_ubms_park <- stan_pcount(formula =  ~ bait 
                                ~ PC1 * hf + PC2 * hf,
                     data = umf_coyote_park,
                     chains = 3,
                     iter = 500,
                     cores = 3)

coyote_nmix_ubms_park

saveRDS(coyote_nmix_ubms_park, file = "coyote_nmix_ubms_park.rds")

plot_effects(coyote_nmix_ubms_park, submodel = "state")
plot_effects(coyote_nmix_ubms_park, submodel = "det")

plot_posteriors(coyote_nmix_ubms_park)
```
```{r}
coyote_pc1_plot_park <- plot_interaction_ubms(
  model = coyote_nmix_ubms_park,
  focal = "PC1",
  moderator = "hf",
  species = "coyote",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "Coyote abundance vs PC1 at low/high HF"
)

coyote_pc1_plot_park
ggsave(filename = "park_coyote_pc2.pdf", coyote_pc1_plot_park, device = "pdf")

```
```{r}
coyote_pc2_plot_park <- plot_interaction_ubms(
  model = coyote_nmix_ubms_park,
  focal = "PC2",
  moderator = "hf",
  species = "coyote",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC2",
  title = "Coyote abundance vs PC2 at low/high HF"
)

coyote_pc2_plot_park
```

##Red Fox
```{r}
##Red Fox
umf_redfox_boreal <- unmarkedFramePCount(
  y = redfoxcounts_boreal,
  siteCovs = covars_boreal,
  obsCovs = list(bait = boreal_bait, camera = boreal_cam)
)

redfox_nmix_stan_boreal <- stan_pcount(formula =  ~ bait
                                ~ PC1 * hf + PC2 * hf,
                     data = umf_redfox_boreal,
                     chains = 3,
                     iter = 500,
                     cores = 3)

redfox_nmix_stan_boreal

saveRDS(redfox_nmix_stan_boreal, file = "redfox_nmix_stan_boreal.rds")


plot_effects(redfox_nmix_stan_boreal, submodel = "state")
plot_effects(redfox_nmix_stan_boreal, submodel = "det")

traceplot(redfox_nmix_stan_boreal, pars=c("beta_state", "beta_det"))
plot_residuals(redfox_nmix_stan_boreal, submodel = "state", covariate = "hf")

plot_posteriors(redfox_nmix_stan_boreal)
```

```{r}
redfox_pc1_plot_boreal <- plot_interaction_ubms(
  model = redfox_nmix_stan_boreal,
  focal = "PC1",
  moderator = "hf",
  species = "red fox",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "Red Fox abundance vs PC1 at low/high HF"
)

redfox_pc1_plot_boreal
```

```{r}
redfox_pc2_plot_boreal <- plot_interaction_ubms(
  model = redfox_nmix_stan_boreal,
  focal = "PC2",
  moderator = "hf",
  species = "red fox",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC2",
  title = "Red Fox abundance vs PC2 at low/high HF"
)

redfox_pc2_plot_boreal
```

```{r}
##Red Fox
umf_redfox_park <- unmarkedFramePCount(
  y = redfoxcounts_park,
  siteCovs = covars_park,
  obsCovs = list(bait = park_bait, camera = park_cam)
)

redfox_nmix_stan_park <- stan_pcount(formula =  ~ bait
                                ~ PC1 * hf + PC2 * hf,
                     data = umf_redfox_park,
                     chains = 3,
                     iter = 500,
                     cores = 3)

redfox_nmix_stan_park

saveRDS(redfox_nmix_stan_park, file = "redfox_nmix_stan_park.rds")

plot_effects(redfox_nmix_stan_park, submodel = "state")
plot_effects(redfox_nmix_stan_park, submodel = "det")

traceplot(redfox_nmix_stan_park, pars=c("beta_state", "beta_det"))
plot_residuals(redfox_nmix_stan_park, submodel = "state", covariate = "hf")

plot_posteriors(redfox_nmix_stan_park)
```

```{r}
redfox_pc1_plot_park <- plot_interaction_ubms(
  model = redfox_nmix_stan_park,
  focal = "PC1",
  moderator = "hf",
  species = "red fox",
  data = covars_park,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "Red Fox abundance vs PC1 at low/high HF"
)

redfox_pc1_plot_park
```

```{r}
redfox_pc2_plot_park <- plot_interaction_ubms(
  model = redfox_nmix_stan_park,
  focal = "PC2",
  moderator = "hf",
  species = "red fox",
  data = covars_park,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "Red Fox abundance vs PC2 at low/high HF"
)

redfox_pc2_plot_park
```

#Lynx
```{r}
##Lynx
umf_lynx <- unmarkedFramePCount(
  y = lynxcounts_boreal,
  siteCovs = covars_boreal,
  obsCovs = list(bait = boreal_bait, camera = boreal_cam)
)

lynx_nmix_stan <- stan_pcount(formula =  ~ bait
                                ~ PC1 * hf + PC2 * hf,
                     data = umf_lynx,
                     chains = 3,
                     iter = 500,
                     cores = 3)

lynx_nmix_stan

saveRDS(lynx_nmix_stan, file = "lynx_nmix_stan.rds")

plot_effects(lynx_nmix_stan, submodel = "state")
plot_effects(lynx_nmix_stan, submodel = "det")

traceplot(lynx_nmix_stan, pars=c("beta_state", "beta_det"))

plot_posteriors(lynx_nmix_stan)

lynx_gof<-gof(lynx_nmix_stan, draws=100)
lynx_gof
plot(lynx_gof)
```

```{r}
lynx_pc1_plot <- plot_interaction_ubms(
  model = lynx_nmix_stan,
  focal = "PC1",
  moderator = "hf",
  species = "lynx",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "Lynx abundance vs PC1 at low/high HF"
)

lynx_pc1_plot
ggsave(filename = "lynx_pc1.pdf", lynx_pc1_plot, device = "pdf")
```

```{r}
lynx_pc2_plot <- plot_interaction_ubms(
  model = lynx_nmix_stan,
  focal = "PC2",
  moderator = "hf",
  species = "lynx",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC2",
  title = "Lynx abundance vs PC2 at low/high HF"
)

lynx_pc2_plot
```

##Plot Coyote, Red Fox, Lynx on one graph
```{r}
plots <- list(
  coyote_boreal_pc1 = plot_interaction_ubms(
      model = coyote_nmix_ubms_boreal,
      focal = "PC1", moderator = "hf",
      species = "coyote", data = covars_boreal,
      ylab = "Abundance", xlab = "Climate PC1",
      title = NULL
    ),
  
  coyote_boreal_pc2 = plot_interaction_ubms(
      model = coyote_nmix_ubms_boreal,
      focal = "PC2", moderator = "hf",
      species = "coyote", data = covars_boreal,
      ylab = "Abundance", xlab = "Climate PC2",
      title = NULL
    ),
    coyote_park_pc1 = plot_interaction_ubms(
      model = coyote_nmix_ubms_park,
      focal = "PC1", moderator = "hf",
      species = "coyote", data = covars_park,
      ylab = "Abundance", xlab = "Climate PC1",
      title = NULL
    ),
  
  coyote_park_pc2 = plot_interaction_ubms(
      model = coyote_nmix_ubms_park,
      focal = "PC2", moderator = "hf",
      species = "coyote", data = covars_park,
      ylab = "Abundance", xlab = "Climate PC2",
      title = NULL
    ),
  
  redfox_boreal_pc1 = plot_interaction_ubms(
      model = redfox_nmix_stan_boreal,
      focal = "PC1", moderator = "hf",
      species = "redfox", data = covars_boreal,
      ylab = "Abundance", xlab = "Climate PC1",
      title = NULL
    ),
  
  redfox_boreal_pc2 = plot_interaction_ubms(
      model = redfox_nmix_stan_boreal,
      focal = "PC2", moderator = "hf",
      species = "redfox", data = covars_boreal,
      ylab = "Abundance", xlab = "Climate PC2",
      title = NULL
    ),
  
  redfox_park_pc1 = plot_interaction_ubms(
    model = redfox_nmix_stan_park,
    focal = "PC1", moderator = "hf",
    species = "redfox", data = covars_park,
    ylab = "Abundance", xlab = "Climate PC1",
    title = NULL
    ),
  
  redfox_park_pc2 = plot_interaction_ubms(
      model = redfox_nmix_stan_park,
      focal = "PC2", moderator = "hf",
      species = "redfox", data = covars_park,
      ylab = "Abundance", xlab = "Climate PC2",
      title = NULL
    ),
  
    lynx_boreal_pc1 = plot_interaction_ubms(
      model = lynx_nmix_stan,
      focal = "PC1", moderator = "hf",
      species = "lynx", data = covars_boreal,
      ylab = "Abundance", xlab = "Climate PC1",
      title = NULL
    ),
  
  lynx_boreal_pc2 = plot_interaction_ubms(
      model = lynx_nmix_stan,
      focal = "PC2", moderator = "hf",
      species = "lynx", data = covars_boreal,
      ylab = "Abundance", xlab = "Climate PC2",
      title = NULL
    )
)

```

```{r}
#Function to add icon
make_icon_grob <- function(species_name, size = 0.30) {
  icon_path <- file.path("data/phylopics", paste0(species_name, ".png"))
  img <- magick::image_read(icon_path)
  rasterGrob(img, width = size, height = size)
}

#Make a region label panel
make_region_label <- function(region_name) {
  ggplot() +
    annotate("text", x = 0.5, y = 0.5, label = region_name, size = 5) +
    theme_void()
}

#Create a left side label strip for each row, comine icon and label vertically
make_row_label <- function(species_name, region_name) {
  icon_panel <- ggplot() +
    annotation_custom(make_icon_grob(species_name),
                      xmin = -Inf, xmax = Inf,
                      ymin = -Inf, ymax = Inf) +
    theme_void() +
    coord_cartesian(clip = "off")

  region_panel <- make_region_label(region_name)

  icon_panel / region_panel   # vertical stack
}
```

```{r}

#Combine row label + PC1 + PC2 into a row
row_coyote_park <- 
  make_row_label("coyote", "Grassland & Parkland") |
  plots$coyote_park_pc1 |
  plots$coyote_park_pc2

row_coyote_boreal <- 
  make_row_label("coyote", "Boreal & Shield") |
  plots$coyote_boreal_pc1 |
  plots$coyote_boreal_pc2

row_redfox_park <- 
  make_row_label("redfox", "Grassland & Parkland") | 
  plots$redfox_park_pc1 | 
  plots$redfox_park_pc2

row_redfox_boreal <- 
  make_row_label("redfox", "Boreal & Shield") | 
  plots$redfox_boreal_pc1 | 
  plots$redfox_boreal_pc2

row_lynx_boreal <- 
  make_row_label("lynx",   "Boreal & Shield") | 
  plots$lynx_boreal_pc1 | 
  plots$lynx_boreal_pc2

#Stack rows into the final grid
grid <- 
  row_coyote_park /
  row_coyote_boreal /
  row_redfox_park /
  row_redfox_boreal /
  row_lynx_boreal

#Remove x axis labels from all but the bottom row
final <- grid +
  plot_annotation(
    tag_levels = NULL,
    theme = theme(
      plot.title = element_text(size = 14)
    )
  ) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank()
  )

#Make a PC1 axis label panel
xlab_pc1 <- ggplot() +
  annotate("text", x = 0.5, y = 0.5, label = "Climate PC1", size = 5) +
  theme_void()

#Make a PC2 axis label panel
xlab_pc2 <- ggplot() +
  annotate("text", x = 0.5, y = 0.5, label = "Climate PC2", size = 5) +
  theme_void()

#Attach them under grid
final <- final /
         (xlab_pc1 | xlab_pc2)



#Add column level x axis labels
final <- grid +
  plot_annotation(
    tag_levels = NULL,
    theme = theme(
      plot.title = element_text(size = 14)
    )
  ) &
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank()
  )

final <- wrap_plots(
  grid,
  widths = c(1, 3, 3),
  guides = "collect"
) +
  plot_annotation(
    title = NULL,
    caption = NULL
  )

#Add shared legend for human footprint
legend <- get_legend(
  plots$coyote_park_pc1 + theme(legend.position = "right")
)

final <- grid | legend

final

ggsave("interactionplots_abmi.pdf", final, width = 7, height = 12)
```

##Marten
```{r}
##marten
umf_marten <- unmarkedFramePCount(
  y = martencounts_boreal,
  siteCovs = covars_boreal,
  obsCovs = list(bait = boreal_bait, camera = boreal_cam)
)

marten_nmix_stan <- stan_pcount(formula =  ~ bait
                                ~ PC1 * hf + PC2 * hf,
                     data = umf_marten,
                     chains = 3,
                     iter = 500,
                     cores = 3)

marten_nmix_stan

saveRDS(coyote_nmix_ubms_park, file = "coyote_nmix_ubms_park.rds")

plot_effects(marten_nmix_stan, submodel = "state")
plot_effects(marten_nmix_stan, submodel = "det")

ubms::traceplot(marten_nmix_stan)
plot_residuals(marten_nmix_stan, submodel = "state", covariate = "hf")

plot_posteriors(marten_nmix_stan)

marten_gof<-gof(marten_nmix_stan, draws=100)
marten_gof
plot(marten_gof)
```

```{r}
marten_pc1_plot <- plot_interaction_ubms(
  model = marten_nmix_stan,
  focal = "PC1",
  moderator = "hf",
  species = "marten",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "marten abundance vs PC1 at low/high HF"
)

marten_pc1_plot
```

```{r}
marten_pc2_plot <- plot_interaction_ubms(
  model = marten_nmix_stan,
  focal = "PC2",
  moderator = "hf",
  species = "marten",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC2",
  title = "marten abundance vs PC2 at low/high HF"
)

marten_pc2_plot
```

##Fisher NMix Models
```{r}
##Fisher
umf_fisher <- unmarkedFramePCount(
  y = fishercounts_boreal,
  siteCovs = covars_boreal,
  obsCovs = list(bait = boreal_bait, camera = boreal_cam)
)

fisher_nmix_stan <- stan_pcount(formula =  ~ bait
                                ~ PC1 * hf + PC2 * hf,
                     data = umf_fisher,
                     chains = 3,
                     iter = 500,
                     cores = 3)

fisher_nmix_stan

saveRDS(coyote_nmix_ubms_park, file = "coyote_nmix_ubms_park.rds")

plot_effects(fisher_nmix_stan, submodel = "state")
plot_effects(fisher_nmix_stan, submodel = "det")

ubms::traceplot(fisher_nmix_stan)
plot_residuals(fisher_nmix_stan, submodel = "state", covariate = "hf")

plot_posteriors(fisher_nmix_stan)

fisher_gof<-gof(fisher_nmix_stan, draws=100)
fisher_gof
plot(fisher_gof)
```

```{r}
fisher_pc1_plot <- plot_interaction_ubms(
  model = fisher_nmix_stan,
  focal = "PC1",
  moderator = "hf",
  species = "fisher",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC1",
  title = "fisher abundance vs PC1 at low/high HF"
)

fisher_pc1_plot
```

```{r}
fisher_pc2_plot <- plot_interaction_ubms(
  model = fisher_nmix_stan,
  focal = "PC2",
  moderator = "hf",
  species = "fisher",
  data = covars_boreal,
  ylab = "Abundance",
  xlab = "Climate PC2",
  title = "fisher abundance vs PC2 at low/high HF"
)

fisher_pc2_plot
```

#Custom N-mixture in Stan
```{r}
#Simulate data for model troubleshooting
set.seed(123)

# core design
n_site    <- 150          # number of sites
min_cam   <- 2
max_cam   <- 4
T         <- 10           # sampling occasions per camera

# number of cameras per site (2–4)
J_site <- sample(min_cam:max_cam, n_site, replace = TRUE)

sum(J_site)  # total cameras

# site-level covariates
clim_pc1 <- rnorm(n_site, 0, 1)
clim_pc2 <- rnorm(n_site, 0, 1)
human_fp       <- rnorm(n_site, 0, 1)  # or runif if you prefer 0–1 scaling

# build camera-level index
site_id_cam <- rep(1:n_site, times = J_site)
n_cam       <- length(site_id_cam)

# baited vs non-baited at camera level (0/1)
bait_cam <- rbinom(n_cam, size = 1, prob = 0.5)

# abundance (lambda) model: log(lambda_i) = beta0 + beta1*pc1 + beta2*pc2 + beta3*hf
beta0 <- 0.5
beta1 <- 0.6
beta2 <- -0.3
beta3 <- 0.4

beta_int1 <- 0.5   # NEW: interaction PC1 × HF
beta_int2 <- -0.4  # NEW: interaction PC2 × HF

phi_true <- 2.0
psi_zero <- 0.15

# detection model: logit(p_ijk) = alpha0 + alpha1*bait_cam_j
alpha0 <- -1.2
alpha1 <- 1.0

sigma_cam <- 0.7
u_cam <- rnorm(n_cam, 0, sigma_cam)

eta_lambda <- beta0 +
  beta1 * clim_pc1 +
  beta2 * clim_pc2 +
  beta3 * human_fp +
  beta_int1 * clim_pc1 * human_fp +   # NEW
  beta_int2 * clim_pc2 * human_fp     # NEW

lambda_site <- exp(eta_lambda)

is_zero <- rbinom(n_site, 1, psi_zero)

N_nb <- rnbinom(n_site, size = phi_true, mu = lambda_site)

N_site <- ifelse(is_zero == 1, 0, N_nb)
summary(N_site)

N_site <- rpois(n_site, lambda_site)
summary(N_site)

inv_logit <- function(x) 1 / (1 + exp(-x))

eta_p_cam <- alpha0 + alpha1 * bait_cam + u_cam
p_cam     <- inv_logit(eta_p_cam)

max_J <- max(J_site)
y <- array(NA_integer_, dim = c(n_site, max_J, T))

cam_counter <- 1
for (i in 1:n_site) {
  Ji <- J_site[i]
  Ni <- N_site[i]
  
  for (j in 1:Ji) {
    p_ij <- p_cam[cam_counter]
    y[i, j, ] <- rbinom(T, size = Ni, prob = p_ij)
    cam_counter <- cam_counter + 1
  }
}

bait_mat <- matrix(0, n_site, max_J)
cam_counter <- 1
for (i in 1:n_site) {
  Ji <- J_site[i]
  bait_mat[i, 1:Ji] <- bait_cam[cam_counter:(cam_counter + Ji - 1)]
  cam_counter <- cam_counter + Ji
}

use_y <- ifelse(!is.na(y), 1L, 0L)

y_fixed <- y
y_fixed[is.na(y_fixed)] <- 0L


stan_data <- list(
  I        = n_site,
  J        = J_site,
  max_J    = max_J,
  max_K    = T,
  y        = y_fixed,
  use_y    = use_y,
  clim_pc1 = clim_pc1,
  clim_pc2 = clim_pc2,
  human_fp = human_fp,
  baited   = bait_mat,
  K        = max(N_site) + 20   # upper bound for N
)


```

```{r}

mod <- cmdstan_model("coyote_nmix.stan")

fit_test <- mod$sample(
  data = stan_data,
  chains = 2,
  parallel_chains = 2,
  iter_warmup = 200,
  iter_sampling = 200,
  adapt_delta = 0.99,
  max_treedepth = 12,
  refresh = 20
)

fit_test$diagnostic_summary()[, c("variable", "rhat", "ess_bulk", "ess_tail", "divergent__", "treedepth__")]


```


```{r}
#Format data
abund <- as.matrix(coyotecounts_boreal)   # cameras × occasions
K      <- ncol(abund)              # number of occasions

site_id   <- covars_boreal$site           # site per camera
sites     <- unique(site_id)
I         <- length(sites)         # number of sites

# cameras per site
J_tab <- table(site_id)
J     <- as.integer(J_tab[match(sites, names(J_tab))])
max_J <- max(J)
max_K <- K

y      <- array(0L, dim = c(I, max_J, max_K))
use_y  <- array(0L, dim = c(I, max_J, max_K))
baited_arr <- matrix(0L, nrow = I, ncol = max_J)

clim_pc1 <- numeric(I)
clim_pc2 <- numeric(I)
human_fp <- numeric(I)

for (i in seq_along(sites)) {
  this_site <- sites[i]
  cams_i    <- which(site_id == this_site)   # row indices in covars/coyotecounts
  J_i       <- length(cams_i)

  # site-level covariates: same for all cameras at this site
  clim_pc1[i] <- covars_boreal$PC1[cams_i[1]]
  clim_pc2[i] <- covars_boreal$PC2[cams_i[1]]
  human_fp[i] <- covars_boreal$hf[cams_i[1]]

  for (j in seq_len(J_i)) {
    row_idx <- cams_i[j]

    # camera-level detection covariate
    baited_arr[i, j] <- as.integer(covars_boreal$baited[row_idx])

    for (k in seq_len(max_K)) {
      val <- abund[row_idx, k]
      if (!is.na(val)) {
        y[i, j, k]     <- as.integer(val)
        use_y[i, j, k] <- 1L
      }
    }
  }
}


stan_data_boreal <- list(
  I       = I,
  J       = J,
  max_J   = max_J,
  max_K   = max_K,
  y       = y,
  use_y   = use_y,
  clim_pc1 = clim_pc1,
  clim_pc2 = clim_pc2,
  human_fp = human_fp,
  baited   = baited_arr,
  K        = 30  # or some upper bound for N
)

```

```{r}
mod_boreal <- cmdstan_model(
  "C:/Users/Gaynor Lab/Documents/abmi_coyotes/coyote_nmix.stan"
)

str(stan_data_boreal, max.level = 1)

stan_data_boreal$J

i <- 1
j <- 1

cbind(
  y      = stan_data$y[i, j, ],
  use_y  = stan_data$use_y[i, j, ]
)

head(stan_data$clim_pc1)
head(stan_data$clim_pc2)
head(stan_data$human_fp)

stan_data_boreal$baited[1, 1:stan_data$J[2]]

stan_data_boreal$K
```
```{r}
system.time(
  fit_test <- mod$sample(
    data = stan_data,
    chains = 1,
    parallel_chains = 1,
    iter_warmup = 5,
    iter_sampling = 5,
    refresh = 1
  )
)

```

```{r}
fit_test <- mod_boreal$sample(
  data = stan_data,
  chains = 1,
  parallel_chains = 1,
  iter_warmup = 200,
  iter_sampling = 200,
  refresh = 20
)

fit_test

MCMCtrace(fit_test)

fit_test$diagnostic_summary()[, c("variable", "rhat", "ess_bulk", "ess_tail", "divergent__", "treedepth__")]


```

```{r}
fit <- mod$sample(
  data = stan_data,
  chains = 2,
  parallel_chains = 2,
  iter_warmup = 300,
  iter_sampling = 300, #Deirdre recommends 4 chains, 3000 warmup, 4000 sampling
  adapt_delta = 0.9,
  max_treedepth = 12,
  refresh = 50
)

#Plot prior and posterior distribution to see how well they line up


```
